apiVersion : apps/v1
kind: Deployment
metadata:
  name: "unpensioncluster-515a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "unpensioncluster-515a"
  template:
    metadata:
      labels:
        app: "unpensioncluster-515a"
    spec:
      containers:
        - name: "unpensioncluster-515a"
          image: "unauthorizationdomain.azurecr.io/unpensioncluster"
          ports:
          - containerPort: 80